
import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { bikes, maintenanceReports, stations, users, commonIssues } from '@/data/mockData';
import { Bike, MapPin, Search, AlertCircle, Calendar, Clock, CheckCircle, Filter, Wrench, BarChart2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import StationMap from '@/components/StationMap';
import { MaintenanceReport } from '@/types';

// Interface for the bike location data
interface BikeLocationInfo {
  id: string;
  name: string;
  location: { latitude: number; longitude: number } | null;
}

const StaffMaintenanceDashboard = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [reports, setReports] = useState<MaintenanceReport[]>([]);
  const [filteredReports, setFilteredReports] = useState<MaintenanceReport[]>([]);
  const [selectedBikeId, setSelectedBikeId] = useState<string | null>(null);
  const [showMap, setShowMap] = useState(false);
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [priorityFilter, setPriorityFilter] = useState<string>('all');
  const [dateFilter, setDateFilter] = useState<string>('all');
  const [typeFilter, setTypeFilter] = useState<string>('all');
  const { toast } = useToast();
  
  useEffect(() => {
    // Staff reports are those generated by staff (role is staff or admin)
    const staffReports = maintenanceReports.filter(report => {
      const reporter = users.find(user => user.id === report.reportedBy);
      return reporter?.role === 'staff' || reporter?.role === 'admin';
    });
    
    setReports(staffReports);
    setFilteredReports(staffReports);
  }, []);
  
  const handleSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchTerm(e.target.value);
    applyFilters(e.target.value, statusFilter, priorityFilter, dateFilter, typeFilter);
  };
  
  const applyFilters = (search: string, status: string, priority: string, date: string, type: string) => {
    let filtered = [...reports];
    
    // Apply search filter
    if (search) {
      filtered = filtered.filter(report =>
        report.description.toLowerCase().includes(search.toLowerCase()) ||
        report.bikeId.toLowerCase().includes(search.toLowerCase()) ||
        report.issue.toLowerCase().includes(search.toLowerCase())
      );
    }
    
    // Apply status filter
    if (status !== 'all') {
      filtered = filtered.filter(report => report.status === status);
    }
    
    // Apply priority filter
    if (priority !== 'all') {
      filtered = filtered.filter(report => report.priority === priority);
    }
    
    // Apply date filter
    if (date === 'today') {
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      filtered = filtered.filter(report => new Date(report.reportedAt) >= today);
    } else if (date === 'week') {
      const weekAgo = new Date();
      weekAgo.setDate(weekAgo.getDate() - 7);
      filtered = filtered.filter(report => new Date(report.reportedAt) >= weekAgo);
    } else if (date === 'month') {
      const monthAgo = new Date();
      monthAgo.setMonth(monthAgo.getMonth() - 1);
      filtered = filtered.filter(report => new Date(report.reportedAt) >= monthAgo);
    }
    
    // Apply issue type filter
    if (type !== 'all') {
      filtered = filtered.filter(report => {
        const issue = commonIssues.find(i => i.name === report.issue);
        return issue?.category.toLowerCase() === type.toLowerCase();
      });
    }
    
    setFilteredReports(filtered);
  };
  
  const handleStatusFilterChange = (value: string) => {
    setStatusFilter(value);
    applyFilters(searchTerm, value, priorityFilter, dateFilter, typeFilter);
  };
  
  const handlePriorityFilterChange = (value: string) => {
    setPriorityFilter(value);
    applyFilters(searchTerm, statusFilter, value, dateFilter, typeFilter);
  };
  
  const handleDateFilterChange = (value: string) => {
    setDateFilter(value);
    applyFilters(searchTerm, statusFilter, priorityFilter, value, typeFilter);
  };
  
  const handleTypeFilterChange = (value: string) => {
    setTypeFilter(value);
    applyFilters(searchTerm, statusFilter, priorityFilter, dateFilter, value);
  };
  
  const handleResolve = (reportId: string) => {
    // Update the status of the report to 'resolved'
    const updatedReports = reports.map(report =>
      report.id === reportId ? { ...report, status: 'resolved' as const, resolvedAt: new Date().toISOString() } : report
    );
    
    setReports(updatedReports);
    
    // Also update the filtered reports
    const updatedFilteredReports = filteredReports.map(report =>
      report.id === reportId ? { ...report, status: 'resolved' as const, resolvedAt: new Date().toISOString() } : report
    );
    setFilteredReports(updatedFilteredReports);
    
    // Find the bike associated with this report and update its status to 'available'
    const report = reports.find(r => r.id === reportId);
    if (report) {
      // In a real app, this would be an API call to update the bike status
      const bikeIndex = bikes.findIndex(b => b.id === report.bikeId);
      if (bikeIndex >= 0) {
        bikes[bikeIndex].status = 'available';
      }
    }
    
    // Show a toast notification
    toast({
      title: 'Issue Resolved',
      description: 'The maintenance issue has been marked as resolved and the bike is now available.',
    });
  };
  
  const handleStartWork = (reportId: string) => {
    // Update the status of the report to 'in-progress'
    const updatedReports = reports.map(report =>
      report.id === reportId ? { ...report, status: 'in-progress' as const } : report
    );
    
    setReports(updatedReports);
    
    // Also update the filtered reports
    const updatedFilteredReports = filteredReports.map(report =>
      report.id === reportId ? { ...report, status: 'in-progress' as const } : report
    );
    setFilteredReports(updatedFilteredReports);
    
    // Show a toast notification
    toast({
      title: 'Work Started',
      description: 'The maintenance issue is now being addressed.',
    });
  };
  
  const handleBikeSelect = (bikeId: string) => {
    setSelectedBikeId(bikeId);
    setShowMap(true);
  };
  
  // Get unique issue categories for filtering
  const issueCategories = Array.from(new Set(commonIssues.map(issue => issue.category)));
  
  const bikeLocations: BikeLocationInfo[] = bikes.map(bike => {
    const station = stations.find(station => station.id === bike.stationId);
    return {
      id: bike.id,
      name: bike.model, // Using model as the name
      location: station ? { 
        latitude: station.coordinates.lat, 
        longitude: station.coordinates.lng 
      } : null,
    };
  }).filter(bike => bike.location !== null) as BikeLocationInfo[];
  
  // Calculate statistics for the staff dashboard
  const totalReports = reports.length;
  const pendingReports = reports.filter(report => report.status === 'pending').length;
  const inProgressReports = reports.filter(report => report.status === 'in-progress').length;
  const resolvedReports = reports.filter(report => report.status === 'resolved').length;
  
  const reportsByPriority = {
    high: reports.filter(report => report.priority === 'high').length,
    medium: reports.filter(report => report.priority === 'medium').length,
    low: reports.filter(report => report.priority === 'low').length,
  };
  
  return (
    <div className="space-y-6">
      <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-graydark dark:text-white">
            <span className="bg-gradient-to-r from-blue-600 to-blue-400 text-transparent bg-clip-text">
              Staff Maintenance Dashboard
            </span>
          </h1>
          <p className="text-muted-foreground dark:text-gray-400">
            Manage and track all staff-reported maintenance issues
          </p>
        </div>
        
        <div className="flex items-center gap-2">
          <Select value={dateFilter} onValueChange={handleDateFilterChange}>
            <SelectTrigger className="w-[120px]">
              <SelectValue placeholder="Date Range" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Dates</SelectItem>
              <SelectItem value="today">Today</SelectItem>
              <SelectItem value="week">This Week</SelectItem>
              <SelectItem value="month">This Month</SelectItem>
            </SelectContent>
          </Select>
          <Button 
            variant="outline" 
            className="gap-1"
            onClick={() => {
              setSearchTerm('');
              setStatusFilter('all');
              setPriorityFilter('all');
              setDateFilter('all');
              setTypeFilter('all');
              setFilteredReports(reports);
            }}
          >
            <Filter size={16} />
            Reset
          </Button>
        </div>
      </div>
      
      {/* Dashboard Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="bg-white shadow-sm border dark:bg-gray-800 dark:border-gray-700">
          <CardContent className="p-6">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Total Reports</p>
                <p className="text-3xl font-bold text-graydark mt-2 dark:text-white">{totalReports}</p>
              </div>
              <div className="p-3 rounded-full bg-blue-100 dark:bg-blue-900">
                <Wrench className="h-6 w-6 text-blue-500 dark:text-blue-300" />
              </div>
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-white shadow-sm border dark:bg-gray-800 dark:border-gray-700">
          <CardContent className="p-6">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Pending</p>
                <p className="text-3xl font-bold text-amber-500 mt-2">{pendingReports}</p>
              </div>
              <div className="p-3 rounded-full bg-amber-100 dark:bg-amber-900">
                <Clock className="h-6 w-6 text-amber-500 dark:text-amber-300" />
              </div>
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-white shadow-sm border dark:bg-gray-800 dark:border-gray-700">
          <CardContent className="p-6">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">In Progress</p>
                <p className="text-3xl font-bold text-blue-500 mt-2">{inProgressReports}</p>
              </div>
              <div className="p-3 rounded-full bg-blue-100 dark:bg-blue-900">
                <Wrench className="h-6 w-6 text-blue-500 dark:text-blue-300" />
              </div>
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-white shadow-sm border dark:bg-gray-800 dark:border-gray-700">
          <CardContent className="p-6">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Resolved</p>
                <p className="text-3xl font-bold text-green-500 mt-2">{resolvedReports}</p>
              </div>
              <div className="p-3 rounded-full bg-green-100 dark:bg-green-900">
                <CheckCircle className="h-6 w-6 text-green-500 dark:text-green-300" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      
      <div className="bg-gray-50 rounded-lg p-4 shadow-sm border dark:bg-gray-800 dark:border-gray-700">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center flex-1">
            <Search className="h-4 w-4 text-gray-500 dark:text-gray-400 mr-2" />
            <Input
              type="text"
              placeholder="Search by bike ID, issue, or description..."
              value={searchTerm}
              onChange={handleSearch}
              className="max-w-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
            />
          </div>
          
          <div className="flex flex-wrap items-center gap-2">
            <Select value={statusFilter} onValueChange={handleStatusFilterChange}>
              <SelectTrigger className="w-[120px]">
                <SelectValue placeholder="Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                <SelectItem value="pending">Pending</SelectItem>
                <SelectItem value="in-progress">In Progress</SelectItem>
                <SelectItem value="resolved">Resolved</SelectItem>
              </SelectContent>
            </Select>
            
            <Select value={priorityFilter} onValueChange={handlePriorityFilterChange}>
              <SelectTrigger className="w-[120px]">
                <SelectValue placeholder="Priority" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Priority</SelectItem>
                <SelectItem value="low">Low</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="high">High</SelectItem>
              </SelectContent>
            </Select>
            
            <Select value={typeFilter} onValueChange={handleTypeFilterChange}>
              <SelectTrigger className="w-[120px]">
                <SelectValue placeholder="Issue Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Types</SelectItem>
                {issueCategories.map((category) => (
                  <SelectItem key={category} value={category.toLowerCase()}>{category}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
      </div>
      
      {showMap && selectedBikeId && (
        <Card className="mb-6 overflow-hidden">
          <CardHeader className="bg-gray-50 dark:bg-gray-800 py-3">
            <CardTitle className="text-lg flex items-center">
              <MapPin className="mr-2" size={18} /> 
              Bike Location: {selectedBikeId}
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <div className="h-[400px]">
              <StationMap 
                stations={bikeLocations}
                selectedStation={selectedBikeId} 
                onStationSelect={(id) => console.log('Selected bike:', id)} 
              />
            </div>
          </CardContent>
        </Card>
      )}
      
      <Tabs defaultValue="all" className="w-full">
        <TabsList className="grid w-full grid-cols-4">
          <TabsTrigger value="all">All</TabsTrigger>
          <TabsTrigger value="pending">Pending</TabsTrigger>
          <TabsTrigger value="in-progress">In Progress</TabsTrigger>
          <TabsTrigger value="resolved">Resolved</TabsTrigger>
        </TabsList>
        
        <TabsContent value="all" className="pt-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {filteredReports.length > 0 ? filteredReports.map(report => (
              <Card key={report.id} className={`bg-white overflow-hidden transition-shadow hover:shadow-md border-l-4
                ${report.priority === 'high' ? 'border-l-error' : 
                  report.priority === 'medium' ? 'border-l-amber-400' : 
                  'border-l-gray-300'}
                dark:bg-gray-800 dark:border-gray-700`}
              >
                <CardHeader className="bg-gray-50 dark:bg-gray-800 py-3">
                  <CardTitle className="flex items-center justify-between text-base">
                    <span className="flex items-center">
                      <Bike className="mr-2 text-gray-500" size={16} /> 
                      <span className="font-semibold">{report.bikeId}</span> 
                      <span className="mx-1">—</span> 
                      {report.issue}
                    </span>
                    <Badge variant={
                      report.status === 'resolved' ? 'outline' :
                      report.status === 'pending' ? 'secondary' : 'default'
                    }>
                      {report.status === 'pending' ? 'Pending' : 
                       report.status === 'in-progress' ? 'In Progress' : 'Resolved'}
                    </Badge>
                  </CardTitle>
                </CardHeader>
                <CardContent className="pt-4">
                  <div className="flex items-start space-x-2 mb-3">
                    <AlertCircle className="h-4 w-4 text-gray-500 mt-0.5" />
                    <p className="text-sm text-gray-700 dark:text-gray-300">{report.description}</p>
                  </div>
                  
                  <div className="flex items-center space-x-2 mb-3">
                    <Clock className="h-4 w-4 text-gray-500" />
                    <div>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Reported: {new Date(report.reportedAt).toLocaleDateString()} 
                        {report.resolvedAt && 
                          ` • Resolved: ${new Date(report.resolvedAt).toLocaleDateString()}`
                        }
                      </p>
                    </div>
                  </div>
                  
                  <div className="flex items-center space-x-2 mb-3">
                    <Calendar className="h-4 w-4 text-gray-500" />
                    <p className="text-xs text-gray-500 dark:text-gray-400">
                      Reported by: {users.find(user => user.id === report.reportedBy)?.name || 'Unknown'}
                    </p>
                  </div>
                  
                  <div className="flex items-center space-x-2">
                    <MapPin className="h-4 w-4 text-blue-500" />
                    <Button variant="link" onClick={() => handleBikeSelect(report.bikeId)} className="p-0 h-auto text-xs font-normal">
                      View Bike Location
                    </Button>
                  </div>
                  
                  {report.status !== 'resolved' && (
                    <div className="flex justify-end mt-4">
                      {report.status === 'pending' ? (
                        <Button 
                          size="sm" 
                          variant="outline"
                          onClick={() => handleStartWork(report.id)}
                          className="text-xs"
                        >
                          <Wrench className="h-3 w-3 mr-1" /> Start Work
                        </Button>
                      ) : (
                        <Button 
                          size="sm" 
                          onClick={() => handleResolve(report.id)}
                          className="text-xs bg-greenprimary hover:bg-greenprimary/80"
                        >
                          <CheckCircle className="h-3 w-3 mr-1" /> Mark as Resolved
                        </Button>
                      )}
                    </div>
                  )}
                </CardContent>
              </Card>
            )) : (
              <div className="col-span-2 p-8 text-center bg-white rounded-lg shadow dark:bg-gray-800">
                <div className="flex flex-col items-center">
                  <AlertCircle className="h-12 w-12 text-gray-300 mb-2" />
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white">No Reports Found</h3>
                  <p className="text-gray-500 mt-1">No maintenance reports match your current filter criteria.</p>
                </div>
              </div>
            )}
          </div>
        </TabsContent>
        
        <TabsContent value="pending" className="pt-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {filteredReports.filter(report => report.status === 'pending').length > 0 ? 
              filteredReports.filter(report => report.status === 'pending').map(report => (
                <Card key={report.id} className={`bg-white overflow-hidden transition-shadow hover:shadow-md border-l-4
                  ${report.priority === 'high' ? 'border-l-error' : 
                    report.priority === 'medium' ? 'border-l-amber-400' : 
                    'border-l-gray-300'}
                  dark:bg-gray-800 dark:border-gray-700`}
                >
                  <CardHeader className="bg-gray-50 dark:bg-gray-800 py-3">
                    <CardTitle className="flex items-center justify-between text-base">
                      <span className="flex items-center">
                        <Bike className="mr-2 text-gray-500" size={16} /> 
                        <span className="font-semibold">{report.bikeId}</span> 
                        <span className="mx-1">—</span> 
                        {report.issue}
                      </span>
                      <Badge variant="secondary">Pending</Badge>
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="pt-4">
                    <div className="flex items-start space-x-2 mb-3">
                      <AlertCircle className="h-4 w-4 text-gray-500 mt-0.5" />
                      <p className="text-sm text-gray-700 dark:text-gray-300">{report.description}</p>
                    </div>
                    
                    <div className="flex items-center space-x-2 mb-3">
                      <Clock className="h-4 w-4 text-gray-500" />
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Reported: {new Date(report.reportedAt).toLocaleDateString()}
                      </p>
                    </div>
                    
                    <div className="flex items-center space-x-2 mb-3">
                      <Calendar className="h-4 w-4 text-gray-500" />
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Reported by: {users.find(user => user.id === report.reportedBy)?.name || 'Unknown'}
                      </p>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <MapPin className="h-4 w-4 text-blue-500" />
                      <Button variant="link" onClick={() => handleBikeSelect(report.bikeId)} className="p-0 h-auto text-xs font-normal">
                        View Bike Location
                      </Button>
                    </div>
                    
                    <div className="flex justify-end mt-4">
                      <Button 
                        size="sm" 
                        variant="outline"
                        onClick={() => handleStartWork(report.id)}
                        className="text-xs"
                      >
                        <Wrench className="h-3 w-3 mr-1" /> Start Work
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )) : (
                <div className="col-span-2 p-8 text-center bg-white rounded-lg shadow dark:bg-gray-800">
                  <div className="flex flex-col items-center">
                    <CheckCircle className="h-12 w-12 text-green-300 mb-2" />
                    <h3 className="text-lg font-medium text-gray-900 dark:text-white">No Pending Reports</h3>
                    <p className="text-gray-500 mt-1">All maintenance issues have been addressed.</p>
                  </div>
                </div>
              )}
          </div>
        </TabsContent>
        
        <TabsContent value="in-progress" className="pt-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {filteredReports.filter(report => report.status === 'in-progress').length > 0 ? 
              filteredReports.filter(report => report.status === 'in-progress').map(report => (
                <Card key={report.id} className={`bg-white overflow-hidden transition-shadow hover:shadow-md border-l-4
                  ${report.priority === 'high' ? 'border-l-error' : 
                    report.priority === 'medium' ? 'border-l-amber-400' : 
                    'border-l-gray-300'}
                  dark:bg-gray-800 dark:border-gray-700`}
                >
                  <CardHeader className="bg-gray-50 dark:bg-gray-800 py-3">
                    <CardTitle className="flex items-center justify-between text-base">
                      <span className="flex items-center">
                        <Bike className="mr-2 text-gray-500" size={16} /> 
                        <span className="font-semibold">{report.bikeId}</span> 
                        <span className="mx-1">—</span> 
                        {report.issue}
                      </span>
                      <Badge>In Progress</Badge>
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="pt-4">
                    <div className="flex items-start space-x-2 mb-3">
                      <AlertCircle className="h-4 w-4 text-gray-500 mt-0.5" />
                      <p className="text-sm text-gray-700 dark:text-gray-300">{report.description}</p>
                    </div>
                    
                    <div className="flex items-center space-x-2 mb-3">
                      <Clock className="h-4 w-4 text-gray-500" />
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Reported: {new Date(report.reportedAt).toLocaleDateString()}
                      </p>
                    </div>
                    
                    <div className="flex items-center space-x-2 mb-3">
                      <Calendar className="h-4 w-4 text-gray-500" />
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Reported by: {users.find(user => user.id === report.reportedBy)?.name || 'Unknown'}
                      </p>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <MapPin className="h-4 w-4 text-blue-500" />
                      <Button variant="link" onClick={() => handleBikeSelect(report.bikeId)} className="p-0 h-auto text-xs font-normal">
                        View Bike Location
                      </Button>
                    </div>
                    
                    <div className="flex justify-end mt-4">
                      <Button 
                        size="sm" 
                        onClick={() => handleResolve(report.id)}
                        className="text-xs bg-greenprimary hover:bg-greenprimary/80"
                      >
                        <CheckCircle className="h-3 w-3 mr-1" /> Mark as Resolved
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )) : (
                <div className="col-span-2 p-8 text-center bg-white rounded-lg shadow dark:bg-gray-800">
                  <div className="flex flex-col items-center">
                    <Wrench className="h-12 w-12 text-gray-300 mb-2" />
                    <h3 className="text-lg font-medium text-gray-900 dark:text-white">No In-Progress Reports</h3>
                    <p className="text-gray-500 mt-1">No maintenance issues are currently being worked on.</p>
                  </div>
                </div>
              )}
          </div>
        </TabsContent>
        
        <TabsContent value="resolved" className="pt-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {filteredReports.filter(report => report.status === 'resolved').length > 0 ? 
              filteredReports.filter(report => report.status === 'resolved').map(report => (
                <Card key={report.id} className="bg-white overflow-hidden transition-shadow hover:shadow-md dark:bg-gray-800 dark:border-gray-700 border-l-4 border-l-green-300">
                  <CardHeader className="bg-gray-50 dark:bg-gray-800 py-3">
                    <CardTitle className="flex items-center justify-between text-base">
                      <span className="flex items-center">
                        <Bike className="mr-2 text-gray-500" size={16} /> 
                        <span className="font-semibold">{report.bikeId}</span> 
                        <span className="mx-1">—</span> 
                        {report.issue}
                      </span>
                      <Badge variant="outline">Resolved</Badge>
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="pt-4">
                    <div className="flex items-start space-x-2 mb-3">
                      <AlertCircle className="h-4 w-4 text-gray-500 mt-0.5" />
                      <p className="text-sm text-gray-700 dark:text-gray-300">{report.description}</p>
                    </div>
                    
                    <div className="flex items-center space-x-2 mb-3">
                      <Clock className="h-4 w-4 text-gray-500" />
                      <div>
                        <p className="text-xs text-gray-500 dark:text-gray-400">
                          Reported: {new Date(report.reportedAt).toLocaleDateString()} 
                          {report.resolvedAt && 
                            ` • Resolved: ${new Date(report.resolvedAt).toLocaleDateString()}`
                          }
                        </p>
                      </div>
                    </div>
                    
                    <div className="flex items-center space-x-2 mb-3">
                      <Calendar className="h-4 w-4 text-gray-500" />
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Reported by: {users.find(user => user.id === report.reportedBy)?.name || 'Unknown'}
                      </p>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <MapPin className="h-4 w-4 text-blue-500" />
                      <Button variant="link" onClick={() => handleBikeSelect(report.bikeId)} className="p-0 h-auto text-xs font-normal">
                        View Bike Location
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )) : (
                <div className="col-span-2 p-8 text-center bg-white rounded-lg shadow dark:bg-gray-800">
                  <div className="flex flex-col items-center">
                    <AlertCircle className="h-12 w-12 text-gray-300 mb-2" />
                    <h3 className="text-lg font-medium text-gray-900 dark:text-white">No Resolved Reports</h3>
                    <p className="text-gray-500 mt-1">No maintenance issues have been resolved yet.</p>
                  </div>
                </div>
              )}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default StaffMaintenanceDashboard;
